name: "BanInfo"
main: TSt\BanInfo\Loader
api: 3.0.1
version: 1.14.1
author: "WeekThor"
description: "Information about banned player or IP and player's ban history"
permissions:
  baninfo.commands.baninfo:
    description: 'Acceess to command /bi'
    default: op
  baninfo.commands.baninfo.ip:
    description: 'Acceess to command /bi-ip'
    default: op
  baninfo.commands.history:
    description: 'Acceess to view player ban history'
    default: op
  baninfo.commands.clearhistory:
    description: 'Acceess to clear player history'
    default: op
  baninfo.commands.bans2history:
    description: 'Acceess to command /bans2history'
    default: op